flores =  [
  { "nome": "Rosa", "cor": "Vermelha", "ano da descoberta": 1800 },
  { "nome": "Orquídea", "cor": "Branca", "ano da descoberta": 1822 },
  { "nome": "Tulipa", "cor": "Amarela", "ano da descoberta": 1600 },
  { "nome": "Margarida", "cor": "Branca", "ano da descoberta": 1700 },
  { "nome": "Girassol", "cor": "Amarela", "ano da descoberta": 1602 },
  { "nome": "Lírio", "cor": "Branco", "ano da descoberta": 1701 },
  { "nome": "Violeta", "cor": "Roxa", "ano da descoberta": 1840 },
  { "nome": "Camélia", "cor": "Rosa", "ano da descoberta": 1809 },
  { "nome": "Jasmim", "cor": "Branco", "ano da descoberta": 1500 },
  { "nome": "Crisântemo", "cor": "Amarela", "ano da descoberta": 1400 },
  { "nome": "Lavanda", "cor": "Roxa", "ano da descoberta": 1800 },
  { "nome": "Dália", "cor": "Vermelha", "ano da descoberta": 1750 },
  { "nome": "Lótus", "cor": "Branca", "ano da descoberta": 3000 },
  { "nome": "Tulipa Negra", "cor": "Preta", "ano da descoberta": 1850 },
  { "nome": "Íris", "cor": "Azul", "ano da descoberta": 1595 },
  { "nome": "Gardênia", "cor": "Branca", "ano da descoberta": 1755 },
  { "nome": "Azaleia", "cor": "Rosa", "ano da descoberta": 1855 },
  { "nome": "Begônia", "cor": "Rosa", "ano da descoberta": 1683 },
  { "nome": "Magnólia", "cor": "Branca", "ano da descoberta": 1681 },
  { "nome": "Amarílis", "cor": "Vermelha", "ano da descoberta": 1770 },
  { "nome": "Anêmona", "cor": "Branca", "ano da descoberta": 1600 },
  { "nome": "Hibisco", "cor": "Vermelho", "ano da descoberta": 1750 },
  { "nome": "Narciso", "cor": "Amarelo", "ano da descoberta": 1776 },
  { "nome": "Miosótis", "cor": "Azul", "ano da descoberta": 1800 },
  { "nome": "Camomila", "cor": "Branca", "ano da descoberta": 1600 },
  { "nome": "Peônia", "cor": "Rosa", "ano da descoberta": 1805 },
  { "nome": "Gerânio", "cor": "Vermelho", "ano da descoberta": 1750 },
  { "nome": "Cinerária", "cor": "Azul", "ano da descoberta": 1900 },
  { "nome": "Bromélia", "cor": "Vermelha", "ano da descoberta": 1870 },
  { "nome": "Dente-de-leão", "cor": "Amarelo", "ano da descoberta": 1700 },
  { "nome": "Lúpulo", "cor": "Verde", "ano da descoberta": 1500 }
]
